variables:
 GIT_SUBMODULE_STRATEGY: recursive    # clone submodules
 GIT_LFS_SKIP_SMUDGE: "1"             # ignore lfs (some problems with vader submodule)
 ROVER_MAIN: '${CI_PROJECT_DIR}'      # all files relative to this.



stages:
  - build
  - test
  - simulation-campaign


# Build all dependencies of the rover project (default: release mode)
# This is the base for running simulation campaings on a dedicated
# gitlab runner with more cores and memmory. Use latest version of containers
build-for-sim:
  stage: build
  tags:
    - rover-sim
  variables:
    INET_M: '${CI_PROJECT_DIR}/inet4'
    LTE_M: '${CI_PROJECT_DIR}/simulte'
    ROVER_M: '${CI_PROJECT_DIR}/rover'
    VEINS_M: '${CI_PROJECT_DIR}/veins'
    VEINS_INET_M: '${CI_PROJECT_DIR}/veins/subprojects/veins_inet'
    MODE: 'release'
    OPP: '${CI_PROJECT_DIR}/scripts/omnetpp exec'
  script:
    # ## update required docker images
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY/rover/rover-main/omnetpp
    - docker pull $CI_REGISTRY/rover/rover-main/sumo
    - docker pull $CI_REGISTRY/rover/rover-main/vadere
    # ## build all models
    - "${OPP} make makefiles"
    - "${OPP} make MODE=${MODE}"
    # ## export inet version
    - "cd ${INET_M}"
    - "export INET_VERSION=$(./_scripts/get_version)"
    # inet> cleanup not needed directories
    - rm -rf doc examples showcases tutorials
    # ## cleanup not needed directories in veins
    - "cd ${VEINS_M}"
    - rm -rf doc examples subprojects/veins_catch subprojects/veins_inet3 subprojects/veins_testsims
    # ## global cleanup
    - "cd ${ROVER_MAIN}"
    - "find . -name \"*.o\" -type f -delete"
    - "cd ${INET_M}"
    # inet> only delete inet sources for artefacts. We may need the other ones.
    - "find . -name \"*.cc\" -type f -delete"
  artifacts:
    paths:
    - ${ROVER_MAIN}/scripts
    - ${ROVER_MAIN}/simulte
    - ${ROVER_MAIN}/inet4
    - ${ROVER_MAIN}/rover
    - ${ROVER_MAIN}/veins
    expire_in: 1 weeks


# run the fingerprint tests
fingerprints:
  stage: test
  tags:
    - rover-sim
  variables:
    OPP: '${CI_PROJECT_DIR}/scripts/omnetpp exec'
  script:
    - "cd ${ROVER_MAIN}/rover/tests/fingerprint"
    - "${OPP} ./fingerprints"
  artifacts:
    paths:
    - ${ROVER_MAIN}/rover/tests/fingerprint
    expire_in: 8 weeks


# run given simulation-campaign
simulation-campaign:
  stage: simulation-campaign
  tags:
    - rover-sim
  rules:
    - if: '$SIM_TRIGGER'
  script:
    - "/bin/bash ${ROVER_MAIN}/$SIM_SCRIPT"
    - "echo ${CI_COMMIT_SHA} > ${ROVER_MAIN}/$SIM_SCRIPT-results/commit-hash"
    - "echo ${CI_PIPELINE_IID} > ${ROVER_MAIN}/$SIM_SCRIPT-results/pipeline-id"
    - "cat /proc/cpuinfo > > ${ROVER_MAIN}/$SIM_SCRIPT-results/cpuinfo"
  artifacts:
    paths:
      - ${ROVER_MAIN}/$SIM_SCRIPT
      - ${ROVER_MAIN}/$SIM_SCRIPT-results
      - ${ROVER_MAIN}/scripts
      - ${ROVER_MAIN}/simulte/src
      - ${ROVER_MAIN}/inet4/src
      - ${ROVER_MAIN}/rover
      - ${ROVER_MAIN}/veins/src
      - ${ROVER_MAIN}/veins/subprojects/veins_inet/src
    expire_in: 60 minutes
