default_language_version:
  python: python3.8

repos:

-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
    - id: nbstripout
      files: ".ipynb"

-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: ["--fast"]

